### ISSUE TITLE
about the ontrastive adversarial samples

### ISSUE THREAD

**Issue by zyfsa** [ExplorerFreda/VSE-C#1]
您好，请问一下您代码中是否只有关于Intra-pair hard negative mining的学习过程，没有包含contrastive adversarial samples的过程吗？另外关于怎么运用对抗性攻击，然后训练的过程，感觉在论文中不是特别明显呢 ，麻烦您解决一下困惑，谢谢

**Comment by ExplorerFreda** [comment]
Thanks for your interest. As stated in README.md, the contrastive samples is constructed by ./adversarial_attack/*.py in advance of the training process. You may view our framework as a two-step method: 
1. generate (linguistic) contrastive adversarial samples (without any model).
2. train with the generated contrastive adversarial samples.

Note: our model is not a GAN.

**Comment by zyfsa** [comment]
@ExplorerFreda  thank you for your reply. Do you mean that you use the generated contrastive adversarial samples as the hard negative samples, then train? the generated contrastive adversarial samples and the hard negative samples are same? please

**Comment by ExplorerFreda** [comment]
In general, if I understand your point correctly, yes. 
More specifically and precisely, some "hard" negative samples should come from the generated adversarial samples, as some generated adversarial samples may not be "hard" enough.

**Comment by zyfsa** [comment]
@ExplorerFreda ,I see, thanks for your reply.
